### ISSUE TITLE
не работает ссылка на тему на форуме в секции About репозитория

### ISSUE THREAD

**Issue by realrushen** [Mr-Dan/AddonUpdater#2]
При переходе по ссылке:
![image](https://github.com/Mr-Dan/AddonUpdater/assets/58989626/4931e6f0-35ee-4d5b-92a8-ec1c58a47b07)
Получаем ответ:
![image](https://github.com/Mr-Dan/AddonUpdater/assets/58989626/1c9d80d1-f1fd-4552-a222-b0045cfb8305)

**Comment by Mr-Dan** [comment]
Тема была удалена с форума

**Comment by Mr-Dan** [comment]
> При переходе по ссылке: ![image](https://user-images.githubusercontent.com/58989626/284046021-4931e6f0-35ee-4d5b-92a8-ec1c58a47b07.png) Получаем ответ: ![image](https://user-images.githubusercontent.com/58989626/284045946-1c9d80d1-f1fd-4552-a222-b0045cfb8305.png)

Тема была удалена с форума
